#!/usr/bin/env bash
# Run pgvector's TAP tests (PostgreSQL::Test::Cluster) the way pgvector's
# `make prove_installcheck` does.
# usage: run-tap.sh {pgrust|ref} [NNN_name.pl ...]   (default: all of test/t)
#   ref:    pure C install ($PG_VEC).
#   pgrust: C initdb creates each cluster, pgrust runs it (hybrid bin dir).
set -euo pipefail
. "$(dirname "$0")/common.sh"

# The hybrid bin dir puts pgrust behind C's pg_ctl:
#  - initdb is NOT here, so PATH finds $PG_TOOLS/bin/initdb, which bootstraps
#    with the C postgres next to it (pgrust has no bootstrap mode).
#  - pg_ctl is a COPY, not a symlink: it looks for "postgres" in its own
#    resolved directory, and that must be the pgrust shim below. Its version
#    check needs `postgres -V` to print exactly "postgres (PostgreSQL) 18.6".
#  - The shim applies pgrust's runtime settings (README quickstart).
make_hybrid_bin() {
  local dir="$1" share
  share="$("$PG_TOOLS/bin/pg_config" --sharedir)"
  mkdir -p "$dir"
  cp "$PG_TOOLS/bin/pg_ctl" "$dir/pg_ctl"
  cat >"$dir/postgres" <<EOF
#!/bin/sh
# Generated by scripts/pgvector/run-tap.sh: run pgrust with its runtime settings.
ulimit -s 65520 2>/dev/null
export PGRUST_PGSHAREDIR='$share'
export PGRUST_TZDIR='$share/timezone'
export RUST_MIN_STACK=33554432
exec '$PGRUST_BIN' "\$@" -c io_method=sync -c max_stack_depth=60000
EOF
  chmod +x "$dir/postgres"
}

[ "$#" -ge 1 ] || die "usage: run-tap.sh {pgrust|ref} [NNN_name.pl ...]"
mode="$1"
shift
out="$PGV_WORK/tap/$mode"
rm -rf "$out"
mkdir -p "$out/prove" "$out/log" "$out/data"

case "$mode" in
  ref) bin_path="$PG_VEC/bin" ;;
  pgrust)
    [ -x "$PGRUST_BIN" ] || die "missing $PGRUST_BIN; run scripts/pgvector/build-pgrust.sh"
    make_hybrid_bin "$out/bin"
    bin_path="$out/bin:$PG_TOOLS/bin"
    ;;
  *) die "unknown mode '$mode' (expected pgrust or ref)" ;;
esac

if [ "$#" -gt 0 ]; then
  tests=()
  for t in "$@"; do tests+=("$PGV_SRC/test/t/$t"); done
else
  tests=("$PGV_SRC"/test/t/*.pl)
fi

: >"$out/summary.tsv"
for t in "${tests[@]}"; do
  [ -f "$t" ] || die "no such TAP test: $t"
  name="$(basename "$t" .pl)"
  if (
    # cwd is the work dir so stray relative writes never reach the reference tree.
    cd "$out"
    export PATH="$bin_path:$PATH"
    export PERL5LIB="$PGV_PERL5LIB${PERL5LIB:+:$PERL5LIB}"
    export TESTDIR="$out" TESTDATADIR="$out/data/$name" TESTLOGDIR="$out/log/$name"
    PG_REGRESS="$(pg_regress_bin)"
    export PG_REGRESS
    prove -v -I "$PG_SRC/src/test/perl" -I "$PGV_SRC/test/perl" "$t"
  ) >"$out/prove/$name.log" 2>&1; then
    printf '%s\tok\n' "$name" | tee -a "$out/summary.tsv"
  else
    printf '%s\tFAIL\n' "$name" | tee -a "$out/summary.tsv"
  fi
done

passed="$(grep -c $'\tok$' "$out/summary.tsv" || true)"
echo "tap ($mode): $passed/${#tests[@]} passed; logs $out/prove and $out/log"
[ "$passed" -eq "${#tests[@]}" ]
