[package]
name = "types_hnsw"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
rustc-hash = { version = "2", default-features = false }
mcx = { path = "../../mcx" }
datum = { path = "../datum" }
types_core = { path = "../types_core" }
types_error = { path = "../types_error" }
types_fmgr = { path = "../fmgr" }
types_tuple = { path = "../types_tuple" }
pairingheap = { path = "../../../backend/lib/pairingheap" }
hashfn = { path = "../../../common/hashfn" }
